version: "3.8"
services:
  db:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '0531'
      MYSQL_DATABASE: chat_dev
    volumes:
      - db_data:/var/lib/mysql
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    networks:
      - app-network

#  app:
#    build:
#      context: .
#    container_name: spring-boot-app
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/chat_dev
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#    depends_on:
#      - db
#    networks:
#      - app-network
#
#networks:
#  app-network:
#
#volumes:
#  db_data:
